markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Sylinx
host: http://sylinx.github.com/
desc: Sylinx

custom:
    category:
        default: Uncategorized
        another: Other
    categories:
      - name:  default
        title: Uncategorized


      - name:  another
        title: Other


meta:
    author:
        name: Sylinx
        email: yanqg@homewaimai.com
        disqus: sylinx              # Disqus缩略标识
        gcse: 006133068628824591854:vbkpwqtvl3e     # Google自定义搜索标识ID
        github: sylinx                # GitHub账号
        gravatar: 0138b33d806287a9b61ebdba22a1f82e  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
